### ISSUE TITLE
Team: Develop teams concept by using MPI comm

### ISSUE THREAD

**Issue by minsii** [pmodels/oshmpi#36]
**Description**: OpenSHMEM 1.5 added the teams concept which is very similar to MPI groups (i.e., a group of processes).  We will develop team management routines in OSHMPI by using MPI group/communicator routines.

Strictly speaking, `team` conceptually equals to `MPI group` and `context` equals to `MPI comm`. But as `team` is directly used by the collective path, we need to create `MPI comm` at team creation. Thus, in practice `team` == `MPI comm`. 

**Suggestion for basic implementation**: Please feel free to optimize if you have a better idea :-)
```
SHMEM_TEAM_MY_PE -> MPI_Comm_rank
SHMEM_TEAM_N_PES -> MPI_Comm_size
SHMEM_TEAM_TRANSLATE_PE -> MPI_Group_translate_ranks

## OpenSHMEM require all PEs in parent group to make the creation call
SHMEM_TEAM_SPLIT_STRIDED -> MPI_Group_range_incl + MPI_Comm_create
SHMEM_TEAM_SPLIT_2D -> likely MPI_Group_range_incl + MPI_Comm_create

SHMEM_TEAM_DESTROY -> MPI_Comm_destroy

## predefined symbols
SHMEM_TEAM_WORLD -> a predefined integer internally maps to dup of MPI_COMM_WORLD
SHMEM_TEAM_SHARED -> a predefined integer internally maps to comm created by
              MPI_Comm_split_type with MPI_COMM_TYPE_SHARED
SHMEM_TEAM_INVALID -> MPI_COMM_NULL
```

**Starting point**:
- Section `9.4 Team Management Routines` in OpenSHMEM [v1.5 spec](http://www.openshmem.org/site/sites/default/site_files/OpenSHMEM-1.5.pdf) 
- Look into `coll_acquire_comm` function in OSHMPI where we already create MPI_Comm for each OpenSHMEM collective call.

**Related tasks**: team-based collectives, team-context-based RMA and AMO 

**Estimated effort**: 2 week

**TODOs**:
- [x] Basic implementation of all above routines
- [x] 1-2 test programs added to tests/ for correctness validation
- [x] Try team management related tests in [SOS test suite](https://github.com/openshmem-org/tests-sos)
